### ISSUE TITLE
Create subscription periods entity

### ISSUE THREAD

**Issue by fabriziovigevani** [aragon/court-subgraph#36]
In order to know if the juror has fees to claim from subscriptions we need to save this information in the subgraph. 
My initial suggestion would be to have the list of periods with all the data (checkPoint, totalActiveBalance, etc). 

I don't think we can have a correspondence between the juror and the amount of fees per period that can claim since is all ensured at the time the [juror claims](https://github.com/aragon/aragon-court/blob/b5362081853732a6f35a98c8683ffbf7ec197fbd/contracts/subscriptions/CourtSubscriptions.sol#L193) .

**Comment by bingen** [comment]
@fabriziovigevani Can we close this for now? (I'm doing it based on our off-line conversation, feel free to open it in case not)
